add commit smoke-test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -248,6 +248,7 @@ jobs:
           name: Get backend url
           command: |
             export BACKEND_IP=$(cat .circleci/ansible/ipec2.txt)
+            echo "${BACKEND_IP}"
             export API_URL="http://${BACKEND_IP}:3030"
             echo "API_URL = ${API_URL}"
             echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
@@ -300,7 +301,104 @@ jobs:
       - revert-migrations
       - destroy-environment
 
+  smoke-test:
+    docker:
+      - image: amazon/aws-cli
+    steps:
+      - checkout
+      - run:
+          name: Install dependencies - Install Ansible 
+          command: |
+            yum install -y curl tar nodejs npm gzip 
+      - attach_workspace:
+          at: .circleci/ansible
+      - run:
+          name: Frontend smoke test.
+          command: |
+            export BACKEND_IP=$(cat .circleci/ansible/ipec2.txt)
+            echo "${BACKEND_IP}"
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}"
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+              echo "-----------Backend test passed---------"
+              exit 0
+            else
+              echo "-----------Backend test failed---------"
+              exit 1
+            fi
+      - run:
+          name: "Backend smoke test"
+          command: |
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+              return 1
+            else
+              return 1
+            fi
+      # Rollback if fail
+      - revert-migrations
+      - destroy-environment
 
+
+  cloudfront-update:
+    docker:
+      - image: amazon/aws-cli
+    steps:
+      - checkout 
+      - run:
+          name: Install dependencies
+          command: |
+            yum install -y curl tar nodejs npm gzip 
+      - run:
+          name: Update cloudfront distribution
+          command: |
+            export OldWorkflowID=$(aws cloudformation \
+              list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+              --no-paginate --output text)
+            echo $OldWorkflowID >> ~/OldWorkflowID.txt
+            cat ~/OldWorkflowID.txt
+            aws cloudformation deploy \
+             --template-file .circleci/files/cloudfront.yml \
+             --stack-name "InitialStack-${OldWorkflowID}" \
+             --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}" \
+             --tags project=udapeople
+            echo OldWorkflowID: "${OldWorkflowID}"
+            echo current Workflow Id: "${CIRCLE_WORKFLOW_ID:0:7}"
+
+  cleanup:
+      docker:
+        - image: amazon/aws-cli
+      steps:
+        - checkout 
+        - run:
+            name: Get old stack workflow id
+            command: |
+              export OldWorkflowID=$(aws cloudformation \
+                list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+                --no-paginate --output text)
+              echo OldWorkflowID: "${OldWorkflowID}"
+              echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
+              ## Fetch the stack names          
+              export STACKS=($(aws cloudformation list-stacks \
+                --query "StackSummaries[*].StackName" \
+                --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
+              echo Stack names: "${STACKS[@]}"  
+        - run:
+            name: Remove old stacks and files
+            command: |
+              if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+              then
+                echo "----------delete-stack----------------"
+                aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+                aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+                aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+              else 
+                echo "----------not found stack delete-----------"
+              fi
+                     
 
 
 workflows:
@@ -326,7 +424,7 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
-#      - smoke-test:
-#          requires: [deploy-frontend, deploy-backend]
-#      - cloudfront-update:
-#          requires: [smoke-test]
+      - smoke-test:
+          requires: [deploy-frontend, deploy-backend]
+      - cloudfront-update:
+          requires: [smoke-test]
